apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app.kubernetes.io/name: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
    spec:
      containers:
        - name: nginx
          image: {{ .Values.appimage }}
          ports:
            - containerPort: 80
          command: ["/bin/echo"]
          args: ["{{ .Values.content }}" ">" "/usr/share/nginx/html/index.html"]